### ISSUE TITLE
Some mistakes in the .md file

### ISSUE THREAD

**Issue by DrVasile** [Anniegavr/DesignThatPattern#1]
1. Please format the headers and sections to look more like a well structure markdown report.
2. The abstract factory is implemented by factories which contain factory methods. It's not correct to say that factory methods implement the abstract factory.
3. You can include the most important snippets of code into the report so that I won't have to go into the files.
4. Btw, it is more common to name packages with lower case letters and separated by dashes.
5. Good luck! :)

**Comment by Anniegavr** [comment]
>About code snippets: I had problems adding images after inserting the 1st one. It simply did not react to any insert action... If it will continue to do so, I will notify you. Meantime, I'll try again.
>I will reformat the text, thank you! (^_^ )
